[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/dashboard.html"
  to = "/dashboard.html"
  status = 200

[[redirects]]
  from = "/admin.html"
  to = "/admin.html"
  status = 200